// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKw2AhpRdQjobRUhD2dkYVs96y_Rl5wT8',
    appId: '1:778353578504:web:1a8b24b1a755b45c7777bd',
    messagingSenderId: '778353578504',
    projectId: 'haian-container',
    authDomain: 'haian-container.firebaseapp.com',
    storageBucket: 'haian-container.firebasestorage.app',
    measurementId: 'G-DSG3Z7223D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvGkGal43A-YYmSoWlmrVdBhYXab31yfw',
    appId: '1:778353578504:android:52f2329974dc4e2c7777bd',
    messagingSenderId: '778353578504',
    projectId: 'haian-container',
    storageBucket: 'haian-container.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvvqOoGuYJa1gM0rerXFl357466EBaHY4',
    appId: '1:778353578504:ios:ed7998d75cfad2437777bd',
    messagingSenderId: '778353578504',
    projectId: 'haian-container',
    storageBucket: 'haian-container.firebasestorage.app',
    iosBundleId: 'com.example.webBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvvqOoGuYJa1gM0rerXFl357466EBaHY4',
    appId: '1:778353578504:ios:ed7998d75cfad2437777bd',
    messagingSenderId: '778353578504',
    projectId: 'haian-container',
    storageBucket: 'haian-container.firebasestorage.app',
    iosBundleId: 'com.example.webBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKw2AhpRdQjobRUhD2dkYVs96y_Rl5wT8',
    appId: '1:778353578504:web:35085b00c6396ce47777bd',
    messagingSenderId: '778353578504',
    projectId: 'haian-container',
    authDomain: 'haian-container.firebaseapp.com',
    storageBucket: 'haian-container.firebasestorage.app',
    measurementId: 'G-1QP3VSR98E',
  );
}
