// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 6.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class AppAssets {
  static const String package = 'web_booking';

  static const String home_svg = 'assets/icons/home.svg';

  static const String users_svg = 'assets/icons/users.svg';

  static const String VesselHA1_jpg = 'assets/images/VesselHA1.jpg';

  static const String hact_logo_png = 'assets/images/hact_logo.png';

  static const String langs_en_EN_json = 'lib/resources/langs/en-EN.json';

  static const String langs_vi_VN_json = 'lib/resources/langs/vi-VN.json';
}
