Map<String, String> en = {
  "_comment_default_page": "Default Page",
  "welcome": "Welcome to Hai An Transport And Stevedoring Joint Stock Company",
  "booking": "Booking",
  "tracking": "Tracking",
  "combine": "Combine",
  "container tracking": "Container Tracking",
  "searchNumber": "B/L No. or Booking No.",
  "schedule": "Schedule",
  "departure": "Departure Location",
  "arrival": "Arrival Location",
  "signin": "Sign In",
  "signup": "Sign Up",
  "inquiry": "Inquiry",
  "_comment_tracking_page": "Tracking Page",
  "title tracking container": "Tracking Container",
  "search": "Search",
  "note_tracking":
      "Our system does not accept House BL numbers assigned by NVOCC or Freight Forwarder.",
  "title_booking": "Booking Detail",
  "seq": "Seq",
  "container": "Container",
  "title_container": "Container Tracking Detail",
  "status_container": "Status",
  "location_container": "Location",
  "eventDate_container": "Event Date",
  "_comment_signup_page": "Sign Up Page",
  "user information": "User Information",
  "user id": "User ID",
  "password": "Password",
  "re password": "Re-enter Password",
  "full name": "Full Name",
  "tel no": "Tel No.",
  "email": "Email",
  "company information": "Company Information",
  "company name": "Company Name",
  "business number": "Business Number",
  "address": "Address",
  "office in charge": "Office in charge",
  "agree to terms": "Agree to terms and conditions",
  "i agree to terms": "I agree to terms and conditions.",
  "create account": "CREATE ACCOUNT",
  "cancle": "Cancle",
  "_comment_signin_page": "Sign In Page",
  "welcome to HAI AN": "Welcome to HAI AN",
  "user name": "User Name",
  "sign in": "SIGN IN",
  "create_account": "Create Account",
  "_comment_userList_page": "User List Page",
  "title user list": "User List",
  "create user": "Create User",
  "save": "Save",
  "create": "Create",
  "user code": "User Code",
  "customer code": "Customer Code",
  "update time": "Update",
  "update user": "Update User",
  "update": "Update",
  "adjust": "Adjust",
  "delete user": "Delete User",
  "delete": "Delete",
  "_comment_CUD_page": "CUD User Page",
  "back": "Back",
  "change password": "Change Password",
  "permissions": "Permissions",
  "error duplicate user": "Error duplicate User Code",
  "fill info ": "Fill in all information in box marked (*)",
  "code": "Code",
  "title dashboard": "Dashboard",
  "all request": "All requirements: ",
  "request wait": "Unprocessed request: ",
  "request approval": "Request approval: ",
  "request reject": "Request reject: ",
  "_comment_approvalList_page": "Approval List Page",
  "approval list": "Approval List",
  "sender": "Sender",
  "pending": "Pending",
  "approve request": "Approve request",
  "request": "Request",
  "content": "Content",
  "container/size": "Container / Size",
  "picture": "Picture",
  "note": "Note",
  "delete note": "Delete note",
  "status approve": "Status",
  "agree combine": "Agree",
  "reject combine": "Reject",
  "_comment_requestList_page": "Request List Page",
  "request list": "Request List",
  "request name": "Request Name",
  "size": "Size",
  "content commitment": "Content of requirements and customer\ncommitments",
  "details": "Details",
  "resend request": "Resend Request Combine",
  "_comment_request_page": "Request Page",
  "send request title": "Send request",
  "send request combine": "Send request combine",
  "attach picture": "Attach picture",
  "upload picture": "Upload picture",
  "customer requests": "Customer requests",
  "customer commitments": "Customer commitments",
  "status request": "Status",
  "send request": "Send request",
  "cont number not exist": "Container number not exist",
  "cont number duplicate":
      "Check your container number in the Checking Combine section",
  "cont number null": "Please enter container number",
  "error": "Error",
  "error maximum 5 picture": "Only pick maximum 5 picture",
  "_comment_checking_combine_page": "Checking Combine Page",
  "checking combine": "Checking Combine",
  "enter container number": "Enter container number",
  "import excel": "Import file excel",
  "domestic": "Domestic",
  "overseas": "Overseas",
  "not found container number": "Not found your container number",
  "only cont types a0 & a1 are combined":
      "Only container types A0 & A1 are combined !",
  "result combine": "Result combine",
  "number of times combine": "Number of times combine",
  "container quality": "Container quality",
  "status": "Status",
  "shipper": "Shipper",
  "result": "Result",
  "remark": "Remark",
  "damage warning": "Damage Warning",
  "note for use: item is packaged": "Note for use: item is packaged",
  "number of times (combine)": "Number of times combine",
  "requests more combine": "Request more combine",
  "_comment_quality_page": "Quality Page",
  "title quality list": "Quality List",
  "title create quality container": "Create Quality Container",
  "title adjust quality container": "Adjust Quality Container",
  "title delete quality container": "Delete Quality Container",
  "quality code": "Quality Code",
  "quality name": "Quality Name",
  "updater": "Updater",
  "_comment_policy_page": "Policy Page",
  "title special policy list": "Special Policy List",
  "title create policy container": "Create Special Policy Container",
  "title adjust policy container": "Adjust Special Policy Container",
  "title delete policy container": "Delete Special Policy Container",
  "times": "Times Combine",
  "shipper code": "Shipper Code",
  "shipper (owner)": "Shipper (Owner)",
  "policy code": "Special Policy Code",
  "policy name": "Special Policy Name",
  "_comment_history_page": "History Page",
  "title history list": "History List",
  "_comment_stock_page": "Stock Page",
  "title container stock": "Container Stock",
  "hello": "Hello !!"
};
