Map<String, String> vi = {
  "_comment_default_page": "Default Page",
  "welcome": "Chào mừng bạn đến với Công Ty TNHH Vận Tải Container Hải An",
  "booking": "Đặt chỗ",
  "tracking": "Vị trí",
  "combine": "Kết hợp",
  "container tracking": "Tra cứu vị trí Container",
  "searchNumber": "Số B/L hoặc số Booking",
  "schedule": "Lịch trình",
  "departure": "Điểm khởi hành",
  "arrival": "Điểm đến",
  "signin": "Đăng nhập",
  "signup": "Đăng ký",
  "inquiry": "Tìm",
  "_comment_tracking_page": "Tracking Page",
  "title tracking container": "Theo dõi Container",
  "search": "Tìm kiếm",
  "note_tracking":
      "Hệ thống không áp dụng với số vận đơn do bên thứ 3 cung cấp.",
  "title_booking": "Thông tin Booking",
  "seq": "STT",
  "container": "Số Container",
  "size_booking": "Kích thước",
  "title_container": "Thông tin vị trí Container",
  "status_container": "Trạng thái",
  "location_container": "Vị trí",
  "eventDate_container": "Thời gian",
  "_comment_signup_page": "Sign Up Page",
  "user information": "Thông tin tài khoản",
  "user id": "Tên đăng nhập",
  "password": "Mật khẩu",
  "re password": "Nhập lại\nmật khẩu",
  "full name": "Họ và tên",
  "tel no": "Số điện thoại",
  "email": "Email",
  "company information": "Thông tin công ty",
  "company name": "Tên công ty",
  "business number": "Số điện thoại công ty",
  "address": "Địa chỉ",
  "office in charge": "Khu vực\nđăng ký",
  "agree to terms": "Agree to terms and conditions",
  "i agree to terms": "I agree to terms and conditions.",
  "create account": "TẠO TÀI KHOẢN",
  "cancle": "Hủy bỏ",
  "_comment_signin_page": "Sign In Page",
  "welcome to HAI AN": "Welcome to HẢI AN",
  "user name": "Tên tài khoản",
  "sign in": "ĐĂNG NHẬP",
  "create_account": "Tạo tài khoản",
  "title user list": "Danh sách tài khoản",
  "create user": "Tạo tài khoản",
  "save": "Lưu",
  "create": "Tạo mới",
  "user code": "Mã tài khoản",
  "customer code": "Mã khách hàng",
  "update time": "Thời gian",
  "update user": "Tài khoản cập nhật",
  "update": "Cập nhật",
  "adjust": "Điều chỉnh",
  "delete user": "Xóa tài khoản",
  "delete": "Xóa",
  "_comment_CUD_page": "CUD User Page",
  "back": "Quay lại",
  "change password": "Đổi mật khẩu",
  "permissions": "Quyền quản trị",
  "error duplicate user": "Mã tài khoản đã có trên hệ thống",
  "fill info ": "Điền đầy đủ thông tin vào các ô có dấu (*)",
  "code": "Mã",
  "title dashboard": "Thông tin chung",
  "all request": "Tổng số yêu cầu: ",
  "request wait": "Yêu cầu chưa xử lý: ",
  "request approval": "Yêu cầu được chấp thuận: ",
  "request reject": "Yêu cầu bị từ chối: ",
  "_comment_approvalList_page": "Approval List Page",
  "approval list": "Danh sách duyệt yêu cầu",
  "sender": "Người gửi",
  "pending": "Chờ duyệt",
  "approve request": "Duyệt yêu cầu",
  "request": "Yêu cầu",
  "content": "Nội dung",
  "container/size": "Container / Kích cỡ",
  "picture": "Ảnh thực tế",
  "note": "Ghi chú hãng tàu",
  "delete note": "Xóa ghi chú",
  "status approve": "Trạng thái duyệt",
  "agree combine": "Đồng ý kết hợp",
  "reject combine": "Từ chối kết hợp",
  "_comment_requestList_page": "Request List Page",
  "request list": "Danh sách yêu cầu",
  "request name": "Tên yêu cầu",
  "size": "Kích cỡ",
  "content commitment": "Nội dung yêu cầu và cam kết khách hàng",
  "details": "Thông tin chi tiết",
  "resend request": "Gửi lại yêu cầu kết hợp",
  "_comment_request_page": "Request Page",
  "send request title": "Gửi yêu cầu",
  "send request combine": "Gửi yêu cầu xin kết hợp",
  "shipper note": "Shipper",
  "attach picture": "Ảnh đính kèm",
  "upload picture": "Tải ảnh lên",
  "customer requests": "Ý kiến khách hàng",
  "customer commitments": "Cam kết khách hàng",
  "status request": "Trạng thái gửi",
  "send request": "Gửi yêu cầu",
  "cont number not exist": "Số Container không tồn tại.",
  "cont number duplicate": "Kiếm tra lại số Container ở mục Kiểm tra kết hợp.",
  "cont number null": "Vui lòng nhập số Container.",
  "error": "Lỗi",
  "error maximum 5 picture": "Chỉ chọn được tối đa 5 ảnh.",
  "_comment_checking_combine_page": "Checking Combine Page",
  "checking combine": "Kiểm tra kết hợp",
  "enter container number": "Nhập số Container",
  "import excel": "Nhập file excel",
  "domestic": "Tuyến nội",
  "overseas": "Tuyến ngoại",
  "not found container number": "Không tìm thấy số Container",
  "only cont types a0 & a1 are combined":
      "Chỉ có container loại A0 và A1 được kết hợp tuyến ngoại !",
  "result combine": "Kết quả kết hợp trả về",
  "number of times combine": "Số lần kết hợp",
  "container quality": "Chất lượng Container",
  "status": "Trạng thái",
  "shipper": "Shipper",
  "result": "Kết quả",
  "remark": "Chú ý",
  "damage warning": "Cảnh báo hư hỏng",
  "note for use: item is packaged": "Lưu ý sử dụng: mặt hàng được đóng",
  "number of times (combine)": "Số lần kết hợp trong chính sách (kết hợp)",
  "requests more combine": "Xin kết hợp thêm vòng",
  "title quote list": "Quote List",
  "title quality list": "Danh sách chất lượng",
  "title create quality container": "Tạo mới chất lượng Container",
  "title adjust quality container": "Chỉnh sửa chất lượng Container",
  "title delete quality container": "Xóa chất lượng Container",
  "quality code": "Mã chất lượng",
  "quality name": "Tên chất lượng",
  "updater": "Người cập nhật",
  "title special policy list": "Danh sách chính sách đặc biệt",
  "title create policy container": "Tạo mới chính sách Container",
  "title adjust policy container": "Chỉnh sửa chính sách Container",
  "title delete policy container": "Xóa chính sách Container",
  "times": "Số lần kết hợp",
  "shipper code": "Mã shipper",
  "shipper (owner)": "Shipper (Chủ hàng)",
  "policy code": "Mã chính sách",
  "policy name": "Tên chính sách",
  "_comment_history_page": "History Page",
  "title history list": "Lịch sử kiểm tra kết hợp",
  "_comment_stock_page": "Stock Page",
  "title container stock": "Danh sách Container",
  "hello": "Xin chào !!",
  "upload image": "Hình ảnh"
};
